### ISSUE TITLE
Persist optional world projection

### ISSUE THREAD

**Issue by jwasilgeo** [ProjectionWizard/projectionwizard.github.io#12]
@beuan please see my recent commits on branch `persist-optional-world-proj`, focusing mainly on:

- changes to [`outputFormat.js`](https://github.com/ProjectionWizard/projectionwizard.github.io/commit/53692f2c758d2379a273b53782c791ad47f489bf#diff-ab0e3e8d6a7290491d39a70eea57c0d1)

- changes to [`previewMap.js`](https://github.com/ProjectionWizard/projectionwizard.github.io/commit/53692f2c758d2379a273b53782c791ad47f489bf#diff-512f49e6d3615509a222670a248e5398)

I sprinkled in some "TODO" comments which would benefit from you taking a look.

**Comment by beuan** [comment]
I addressed all TODOs and do some other changes to your code. See commit https://github.com/ProjectionWizard/projectionwizard.github.io/commit/e04595d854260e25912e476c679ed591031486f4.

This appears to be done. Can you please review the changes and make PR if you think it is done? Thanks you, @jwasilgeo!
