### ISSUE TITLE
Additional ideas and fixes

### ISSUE THREAD

**Issue by ProjectionWizard** [ProjectionWizard/projectionwizard.github.io#19]
- [x] Add option to display geographic extent on the preview map (fixed with https://github.com/ProjectionWizard/projectionwizard.github.io/commit/05cf0863ee623317c76e5faf6c6fc4f42f17cdea and https://github.com/ProjectionWizard/projectionwizard.github.io/commit/c9c16851d4347869f3424cc3b13a94ddc0d1642)
- [x] Snap the rectangle to a pole when it is on the edge of Web Mercator (fixed with https://github.com/ProjectionWizard/projectionwizard.github.io/commit/6602620fe94413aefb5bfa85dda06dd60496324b)
- [x] Add option to display origin points on the preview map (fixed with  https://github.com/ProjectionWizard/projectionwizard.github.io/commit/8dd37ef61dcdf39a67250689ad81435d2acbe5eb)
- [x] Adding Cassini projection for regional equidistant maps with an north-south extent (fixed with https://github.com/ProjectionWizard/projectionwizard.github.io/commit/559009c08d8d4321328f00de49d07c5dc3061375)
- [x] PROJ alias for Plate Carrée is `eqc` and not `latlong` (fixed with https://github.com/ProjectionWizard/projectionwizard.github.io/commit/559009c08d8d4321328f00de49d07c5dc3061375)
- [x] Replace Plate Carrée with equidistant cylindrical projection for equidistant maps near the Equator (fixed with https://github.com/ProjectionWizard/projectionwizard.github.io/commit/559009c08d8d4321328f00de49d07c5dc3061375)
- [x] For hemisphere maps when extent is in [tropics](https://en.wikipedia.org/wiki/Tropics), return a cylindrical projection. (fixed with https://github.com/ProjectionWizard/projectionwizard.github.io/commit/fc4e94927ca0028a67a2f7ccceb9dbe84985344c)
- [x] Move _Help_ and _Customize_ buttons inside the container, floating above the map (fixed with https://github.com/ProjectionWizard/projectionwizard.github.io/commit/a7f60ddd6fa81a2de2b92470870ae2190ed315f1)
- [x] Add "Customize Options" topic to help dialog text (fixed with https://github.com/ProjectionWizard/projectionwizard.github.io/commit/4a3c32ef177d66c236153b460d130302985060c7)
- [x] Update help dialog for changes in #18 and #19 (fixed with https://github.com/ProjectionWizard/projectionwizard.github.io/commit/4a3c32ef177d66c236153b460d130302985060c7)

**Comment by ProjectionWizard** [comment]
Changes prepared in [`suggestions-4`](https://github.com/ProjectionWizard/projectionwizard.github.io/compare/suggestions-4) branch.

**Comment by beuan** [comment]
Changes ready in [`suggestions-4`](https://github.com/ProjectionWizard/projectionwizard.github.io/compare/suggestions-4) branch.
