### ISSUE TITLE
Continuous canvas updates

### ISSUE THREAD

**Issue by jwasilgeo** [ProjectionWizard/projectionwizard.github.io#4]
@beuan, as you know work in progress is over on branch [`continuous-canvas-updates`](https://github.com/ProjectionWizard/projectionwizard.github.io/tree/continuous-canvas-updates).

I sprinkled my ongoing changes with several "TODO" comments.  One in specific I'd like you to look at is this one if you can.

https://github.com/ProjectionWizard/projectionwizard.github.io/blob/6f8b6f6a3b21b017ad2e9b67717a4fa9de011da7/previewMap.js#L259-L260

 While interacting with the leaflet map, the continuous d3 canvas map updates are not the same sometimes as the final settled state of the d3 canvas map when you are finished interacting.

**Comment by beuan** [comment]
@jwasilgeo, can you send me an example of values? Tnx.

**Comment by beuan** [comment]
@jwasilgeo, I just checked your video and the issue makes sense. This should not be happening. 
I noticed that everything looks OK when you dragging one vertex, but when you are dragging whole rectangle something is not updating right. I am suspecting that something is wrong with the center of the preview map not being updated when rectangle is drag around. It might be that proper callback needs to be added to dragging.
https://github.com/ProjectionWizard/projectionwizard.github.io/blob/6f8b6f6a3b21b017ad2e9b67717a4fa9de011da7/map.js#L325-L337

**Comment by beuan** [comment]
@jwasilgeo, I just pushed the fix for continuous D3 canvas updates to your [`continuous-canvas-updates`](https://github.com/ProjectionWizard/projectionwizard.github.io/tree/continuous-canvas-updates) branch. See https://github.com/ProjectionWizard/projectionwizard.github.io/commit/5c9fe789db2365f664d3904b4830d40a361758bb commit.
